# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='latitud',
            field=models.CharField(default=datetime.datetime(2016, 4, 7, 18, 36, 18, 630000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrado',
            name='longitud',
            field=models.CharField(default=datetime.datetime(2016, 4, 7, 18, 36, 30, 566000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
