# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_auto_20160407_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
