# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_auto_20160411_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='myfolder/'),
        ),
    ]
